### ISSUE TITLE
PNG issue with version 2.12.1

### ISSUE THREAD

**Issue by peterstadler** [robcast/digilib#60]
Hi @robcast,
many thanks for this great piece of software that we happily use for several projects and for several years now!

Now to the issue:
With the update to version 2.12.1 I get an error when trying to process the PNG file at https://weber-gesamtausgabe.de/Scaler/IIIF/persons%2FA0020xx%2FA002068%2FWeber-Medaille.png/full/full/0/native.jpg to JPG:

```
09:47:26.954 [pool-3-thread-2] ERROR digilib.scaler - Other error:
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_212]
at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_212]
at javax.imageio.metadata.IIONodeList.item(IIOMetadataNode.java:127) ~[?:1.8.0_212]
at digilib.image.ImageLoaderDocuImage.getPngColorProfile(ImageLoaderDocuImage.java:666) ~[digilib-common-2.12.1.jar:?]
at digilib.image.ImageLoaderDocuImage.loadSubimage(ImageLoaderDocuImage.java:757) ~[digilib-common-2.12.1.jar:?]
at digilib.image.ImageWorker.call(ImageWorker.java:116) ~[digilib-common-2.12.1.jar:?]
at digilib.servlet.AsyncServletWorker.run(AsyncServletWorker.java:105) [digilib-servlet3-2.12.1.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

The manifest is served ok: https://weber-gesamtausgabe.de/Scaler/IIIF/persons%2FA0020xx%2FA002068%2FWeber-Medaille.png/info.json
And the native output is ok, too: https://weber-gesamtausgabe.de/Scaler/IIIF/persons%2FA0020xx%2FA002068%2FWeber-Medaille.png/full/full/0/native

Might this be related to the latest work on color profiles or is the error somewhere on my end? Many thanks for any help in advance!

**Comment by robcast** [comment]
The Exception you show is related to the new PNG color profile support but there was also an issue with the JPEG output for some image types. I could not reproduce your exact error on my system.

I tried to fix both issues in https://github.com/robcast/digilib/commit/dff11a3121f5ed363c39e85c100d5b503eb5b187 can you try out the current master branch? Are you building from source or use Maven or Docker?

P.S. It looks like you run on Java 8 which is supported but I would suggest to use Java 11 for digilib where the underlying Java2D implementation works better in some ways.

**Comment by peterstadler** [comment]
Indeed it turned out I was using an ancient Docker base image and JRE. Switching to a current image with JRE11 (and the current Digilib release version) solved it for me. 

Many thanks for the quick response!
